---
- name: Copy all bin config templates
  template:
    src: "{{ item }}"
    dest: "{{ bitbucket_install_dir }}/atlassian-bitbucket-{{ bitbucket_version }}/bin/{{ item | basename | splitext | first }}"
    owner: "{{ bitbucket_user }}"
    group: "{{ bitbucket_group }}"
    mode: 0755
  with_fileglob:
    - templates/bin/*
  notify: restart bitbucket
  tags: bitbucket_configure

- name: Copy JMX template if enabled
  template:
    src: jmx/set-jmx-opts.sh.j2
    dest: "{{ bitbucket_install_dir }}/atlassian-bitbucket-{{ bitbucket_version }}/bin/set-jmx-opts.sh"
    owner: "{{ bitbucket_user }}"
    group: "{{ bitbucket_group }}"
    mode: 0755
  notify: restart bitbucket
  when: bitbucket_jmx.enabled
  tags: bitbucket_configure

- name: Copy JMX password file if password secured
  template:
    src: jmx/jmx.access.j2
    dest: "{{ bitbucket_jmx.remote_auth.password_file }}"
    owner: "{{ bitbucket_user }}"
    group: "{{ bitbucket_group }}"
    mode: 0600
  notify: restart bitbucket
  when: bitbucket_jmx.enabled and bitbucket_jmx.remote_auth.type=="password"
  no_log: true
  tags: bitbucket_configure

- name: Copy Bitbucket properties
  template:
    src: "{{ bitbucket_properties_template_path }}"
    dest: "{{ bitbucket_home_dir }}/shared/bitbucket.properties"
    owner: "{{ bitbucket_user }}"
    group: "{{ bitbucket_group }}"
    mode: 0644
  notify: restart bitbucket
  tags: bitbucket_configure

- name: Change log rotation policy
  replace:
    path: "{{ bitbucket_install_dir }}/atlassian-bitbucket-{{ bitbucket_version }}/app/WEB-INF/classes/logback.xml"
    regexp: '\d+\<\/maxHistory>'
    replace: "{{ bitbucket_logrotate_maxhistory }}</maxHistory>"
    backup: yes
  notify: restart bitbucket
  tags: bitbucket_configure
  when: bitbucket_version is version('7.0.0', '<')
