---
bitbucket_java_home: "{{ java_open_jdk_home }}"
bitbucket_jmx:
  enabled: true
  remote_port: 3333
  rmi_server_hostname: "{{ inventory_hostname }}"
  remote_rmi_port: 9999
  remote_auth:
    type: password  # [password, ssl]
    # if type: password, these variables are needed
    password: notapassword
    password_file: "{{ bitbucket_install_dir }}/atlassian-bitbucket-{{ bitbucket_version }}/bin/notapasswordfile"

bitbucket_plugins:
  - name: bit-booster-commit-graph-2020.09.05.jar
    url: https://marketplace.atlassian.com/download/apps/1219256/version/202009055
  - name: bitbucket-web-post-receive-hooks-plugin-4.0.0.jar
    url: https://marketplace.atlassian.com/download/apps/1211539/version/400000000
